obo: ncbitaxon.owl ncbitaxon.obo taxslim.owl

ncbitaxon.owl:
	wget http://purl.obolibrary.org/obo/ncbitaxon.owl

ncbitaxon.obo:
	wget http://purl.obolibrary.org/obo/ncbitaxon.obo

taxslim.owl:
	wget http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl
